# Generated by Django 5.1.4 on 2024-12-18 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=15)),
                ('ville', models.CharField(max_length=40)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='RegimeAlimentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('smalldescription', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.CharField(max_length=40)),
                ('produit_frais', models.BooleanField(default=False)),
                ('produit_bio', models.BooleanField(default=False)),
                ('produit_vegan', models.BooleanField(default=False)),
                ('produit_sans_gluten', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
                ('regime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.regimealimentaire')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_achat', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(default='http://photo')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shop.commande')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime_alimentaire_prefere', models.CharField(choices=[('vegan', 'Vegan'), ('vegetarien', 'Végétarien'), ('sans_gluten', 'Sans-Gluten'), ('paleolithique', 'Paléolithique (Paleo)'), ('mediterraneen', 'Méditerranéen'), ('cetogene', 'Cétogène (Keto)')], max_length=20)),
                ('preferred_categories', models.ManyToManyField(to='shop.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
