# Generated by Django 5.1.4 on 2025-01-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_commande_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='addressli',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
