# Generated by Django 5.1.4 on 2024-12-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_is_bio_product_is_fresh_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_bio',
            new_name='produit_bio',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_fresh',
            new_name='produit_frais',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_gluten_free',
            new_name='produit_sans_gluten',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_vegan',
            new_name='produit_vegan',
        ),
    ]
