# Generated by Django 5.1.4 on 2025-01-15 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_commande_addressli'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='prenom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('shipped', 'Expédiée'), ('delivered', 'Livrée')], default='pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='commande',
            name='ville',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='smalldescription',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profileutilisateur',
            name='regime_alimentaire_prefere',
            field=models.CharField(choices=[('vegan', 'Vegan'), ('vegetarien', 'Végétarien'), ('sans_gluten', 'Sans-Gluten'), ('paleolithique', 'Paléolithique (Paleo)'), ('mediterraneen', 'Méditerranéen'), ('cetogene', 'Cétogène (Keto)')], max_length=90),
        ),
        migrations.AlterField(
            model_name='regimealimentaire',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
