# Generated by Django 5.1.4 on 2024-12-16 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_is_bio_product_produit_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegimeAlimentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='regime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regimes', to='shop.regimealimentaire'),
        ),
    ]
