# Generated by Django 5.1.4 on 2025-02-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_commande_user_alter_category_nom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Smalldescription', models.TextField(null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_add'],
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='nom_prenom_destinataire',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='numero_destinataire',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
