# Generated by Django 5.1.4 on 2024-12-16 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='ProfileUtilisateur',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='date_of_purchase',
            new_name='date_achat',
        ),
        migrations.RenameField(
            model_name='profileutilisateur',
            old_name='preferred_diet',
            new_name='regime_alimentaire_prefere',
        ),
    ]
